baseURL = "http://adwsingh.github.io"
languageCode = "en-us"
title = "</adwsingh>"
theme = "kiss"
enableRobotsTXT = true
copyright = "&copy; <a href=\"https://github.com/adwsingh\">Adwait Kumar Singh</a> 2021<p><small>The opinions expressed on this website are my own,<br>and are not associated with any employers, past or present.</small>"
googleAnalytics = "G-L7XXS6WEC2"
disqusShortname = "adwsingh-com"

[params.info]
enableSocial = true
homeTitle = "adwait's blog"
related = true
codeCopy = true
taxonomiesCount = true

[params.social]
github = "adwsingh"
email = "adwsingh@gmail.com"
linkedin = "adwait-kumar-singh-b5321512a"
facebook = "adwait.kumarsingh.1"
stackoverflow = "1432247/adwait-kumar"

[taxonomies]
tag = "tags"

[params.social.config]
platforms = ["github", "stackoverflow", "facebook", "twitter", "instagram", "email", "codepen", "linkedin", "about"]